### ISSUE TITLE
segmentation fault on linux x86_64

### ISSUE THREAD

**Issue by ghost** [hjr3/php-rpm#5] opened 2017-08-19 10:43 UTC
i got this

  Compiling php-sys v0.1.0 (file:///root/php-rpm/php-sys)
   Compiling php-rpm v0.1.0 (file:///root/php-rpm)
error[E0425]: cannot find value `sapi_globals` in module `ffi`
  --> src/sapi.rs:76:14
   |
76 |         ffi::sapi_globals.sapi_headers.http_response_code = 200;
   |              ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
  --> src/sapi.rs:79:14
   |
79 |         ffi::sapi_globals.server_context = context_ptr as *mut c_void;
   |              ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
  --> src/sapi.rs:84:28
   |
84 |         let context = ffi::sapi_globals.server_context as *mut ServerContext;
   |                            ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
  --> src/sapi.rs:90:37
   |
90 |         drop(CString::from_raw(ffi::sapi_globals.request_info.cookie_data));
   |                                     ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
  --> src/sapi.rs:91:14
   |
91 |         ffi::sapi_globals.server_context = ptr::null_mut();
   |              ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:143:10
    |
143 |     ffi::sapi_globals.request_info = request_info;
    |          ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:163:24
    |
163 |     let context = ffi::sapi_globals.server_context as *mut ServerContext;
    |                        ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:171:13
    |
171 |     if ffi::sapi_globals.headers_sent == 1 {
    |             ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:197:24
    |
197 |     let context = ffi::sapi_globals.server_context as *mut ServerContext;
    |                        ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:227:10
    |
227 |     ffi::sapi_globals.headers_sent = 1;
    |          ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:236:24
    |
236 |     let context = ffi::sapi_globals.server_context as *mut ServerContext;
    |                        ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:263:24
    |
263 |     let context = ffi::sapi_globals.server_context as *mut ServerContext;
    |                        ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error[E0425]: cannot find value `sapi_globals` in module `ffi`
   --> src/sapi.rs:325:24
    |
325 |     let context = ffi::sapi_globals.server_context as *mut ServerContext;
    |                        ^^^^^^^^^^^^ did you mean `sapi_globals_id`?

error: aborting due to 13 previous errors

error: Could not compile `php-rpm`.

To learn more, run the command again with --verbose.

**Comment by hjr3** [comment] 2017-08-19 15:49
I believe you have ZTS enabled. I do not support this at the moment, but will be adding it soon. The issue is that PHP internals use pre-processor definitions such as `SG()` to branch on whether ZTS is enabled.

To check this for sure, please paste me the output from `php-config`.

**Comment by ghost** [comment] 2017-08-20 07:32
You are right. After configure like this (non-ts, dynamically linked),  i can compile php-rpm right now.
But chrome complains with `ERR_EMPTY_RESPONSE` and php-rpm just exits with `segment fault`.

```
./buildconf --force
CC=clang CXX=clang++ CFLAGS="-P -fPIC" ./configure --prefix=/usr \
--enable-static=no --enable-shared=yes \
--enable-embed=shared --disable-debug --disable-cli --disable-cgi
```

OS: Debian stable x86_64 with php 7.2.0, built with clang/gcc (have tried both).

I'd say this is an amazing project by combining the most easy language with a fastest back-end, thanks for your work.

**Comment by hjr3** [comment] 2017-08-20 15:09
@di3663 I am glad you find it useful. My simple php script in `tests/index.php` works in chrome.

Please make sure you are using the latest version. Can you run with `RUST_BACKTRACE=1` and `RUST_LOG=php_rpm` so I can see where the segfault is? Example:

```
RUST_BACKTRACE=1 RUST_LOG=php_rpm cargo run -- /path/to/document/root
```

And if possible, include the php script you are using?

**Comment by ghost** [comment] 2017-08-20 16:09
# output1
php-config
```
/php_7.2.0 # php-config 
Usage: /usr/bin/php-config [OPTION]
Options:
  --prefix            [/usr]
  --includes          [-I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib]
  --ldflags           []
  --libs              [-lcrypt   -lzip -lzip -lz -lresolv -lcrypt -lrt -lz -lldap -llber -lstdc++ -lgd -lpng -lz -ljpeg -lpng -lz -ljpeg -lcurl -lbz2 -lz -lpcre -lrt -lm -ldl -lnsl  -lxml2 -lz -llzma -liconv -lm -ldl -lssl -lcrypto -lssl -lcrypto -lcurl -lxml2 -lz -llzma -liconv -lm -ldl -lssl -lcrypto -lfreetype -lfreetype -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI -licui18n -licuuc -licudata -licuio -lmemcached -lmemcachedutil -lsasl2 -lxml2 -lz -llzma -liconv -lm -ldl -lxml2 -lz -llzma -liconv -lm -ldl -lcrypt -lxml2 -lz -llzma -liconv -lm -ldl -lxml2 -lz -llzma -liconv -lm -ldl -lxml2 -lz -llzma -liconv -lm -ldl -lxml2 -lz -llzma -liconv -lm -ldl -lxml2 -lz -llzma -liconv -lm -ldl -lzmq -lssl -lcrypto -lcrypt ]
  --extension-dir     [/usr/lib/extensions/no-debug-non-zts-20170718]
  --include-dir       [/usr/include/php]
  --man-dir           [/usr/php/man]
  --php-binary        [NONE]
  --php-sapis         [ embed phpdbg]
  --configure-options [--prefix=/usr --libdir=/usr/lib --includedir=/usr/include --sysconfdir=/etc --enable-static=no --enable-shared=yes --enable-embed=shared --disable-debug --disable-cli --disable-cgi --enable-opcache --enable-zend-signals --enable-bcmath --enable-calendar --enable-fileinfo --enable-inotify --with-png-dir=/usr --with-jpeg-dir=/usr --with-freetype-dir=/usr --with-gd=/usr --with-imagick=/usr --enable-exif --enable-phar --with-zlib-dir=/usr --with-bz2=/usr --with-libzip=/usr --enable-zip --with-openssl --with-crypto --with-mhash=/usr --with-curl=/usr --with-libxml-dir=/usr --enable-xml --enable-dom --with-xmlrpc --enable-json --enable-soap --enable-sockets --enable-ftp --enable-mailparse --with-ldap=/usr --enable-intl --enable-mbstring --enable-mbregex --with-pcre-regex=/usr --enable-pcntl --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-memcached --enable-redis --with-pdo-sqlite --with-pdo-mysql --with-mysqli --enable-mysqlnd --enable-ds --enable-wddx]
  --version           [7.2.0beta3]
  --vernum            [70200]

```


# output2
RUST_BACKTRACE=1 RUST_LOG=php_rpm cargo run -- tests
```
    Finished dev [unoptimized + debuginfo] target(s) in 190.82 secs
     Running `target/debug/php-rpm tests`
Listening on 127.0.0.1:3000
TRACE:php_rpm::sapi: read_cookies
TRACE:php_rpm::sapi: sapi_server_register_varibles
TRACE:php_rpm::sapi: sapi_server_send_headers
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: read_post
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
TRACE:php_rpm::sapi: sapi_server_ub_write
~/php-rpm # 

```

![_2017-08-20_16-05-51](https://user-images.githubusercontent.com/20258455/29496403-83a82d8a-85c1-11e7-9a32-f17045ae9ec3.png)


Contains no useful info, does it help?

**Comment by hjr3** [comment] 2017-08-21 00:48
@di3663 Thank you. I will get a debian instance up and get a fix!

**Comment by hjr3** [comment] 2017-08-21 15:12
@di3663 this issue should be fixed now.

**Closed as completed** 2017-08-21 15:12 UTC
