### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by ghost** [hjr3/php-rpm#11] opened 2017-10-13 09:18 UTC
linux os
```
3.10.0-514.10.2.el7.x86_64 
```

rustc --version
```
rustc 1.21.0 (3b72af97e 2017-10-09)
```

run
```
C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/ LD_LIBRARY_PATH=/root/xx/BIN/usr/lib64 LIBCLANG_PATH=/root/xx/BIN/usr/lib64 cargo build
```

1. without dependences updated
```
   Compiling php-sys v0.1.0 (file:///root/xx/php-rpm/php-sys)
error: linking with `cc` failed: exit code: 1
...
  = note: /root/xx/php-rpm/target/debug/deps/php_rpm-d8aacc3cd1b878d7.0.o: In function `php_rpm::sapi::php_startup':
          /root/xx/php-rpm/src/sapi.rs:148: undefined reference to `zend_signal_startup'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `php-rpm`.

To learn more, run the command again with --verbose.
```

2.with dependences updated
```
error[E0614]: type `std::option::Option<&mut php::_IO_FILE>` cannot be dereferenced
  --> src/sapi.rs:77:9
   |
77 |         *handle.fp.as_mut() = fp;
   |         ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `php-rpm`.

To learn more, run the command again with --verbose.
```

**Comment by ghost** [comment] 2017-10-13 09:21
/usr/bin/php-config
```
Usage: /usr/bin/php-config [OPTION]
Options:
  --prefix            [/usr]
  --includes          [-I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib]
  --ldflags           []
  --libs              [-lcrypt   -lresolv -lcrypt -lrt -lrt -lm -ldl -lnsl  -lpthread -lxml2 -lz -lm -ldl -lxml2 -lz -lm -ldl -lxml2 -lz -lm -ldl -lcrypt -lxml2 -lz -lm -ldl -lxml2 -lz -lm -ldl -lxml2 -lz -lm -ldl -lcrypt ]
  --extension-dir     [/usr/lib/php/extensions/no-debug-zts-20160303]
  --include-dir       [/usr/include/php]
  --man-dir           [/usr/php/man]
  --php-binary        [NONE]
  --php-sapis         [ embed]
  --configure-options [--prefix=/usr --enable-mbstring --enable-maintainer-zts --enable-static=no --enable-shared=yes --enable-embed=shared --disable-debug --disable-cli --disable-cgi --disable-phpdbg --enable-redis=static]
  --version           [7.1.10]
  --vernum            [70110]
```

**Comment by hjr3** [comment] 2017-10-14 15:56
There is some weird stuff going on in upstream: https://bugs.php.net/bug.php?id=71041

The current fix is to apply:

```
sed -e 's/void zend_signal_startup/ZEND_API void zend_signal_startup/g' -ibk Zend/zend_signal.c Zend/zend_signal.h
```

edit: actually https://bugs.php.net/bug.php?id=74149 says this is fixed in 7.1.2. Let me see what is going on.

**Comment by hjr3** [comment] 2017-10-14 16:44
@di3663 It took me a while to remember what the issue was. The `zend_signal_startup` function is extern, but it does not have `ZEND_API`. I have to manually patch that until upstream php resolves their issue.

I built against php-7.1.10 and could not reproduce the issue with `*handle.fp.as_mut() = fp;` not working. The build is [here](https://travis-ci.org/hjr3/php-rpm/jobs/287967027). Can you tell me what dependencies you updated in your step 2?

**Comment by hjr3** [comment] 2017-10-14 18:12
I opened https://github.com/php/php-src/pull/2854 to try and fix the upstream issue with zend signals.

**Comment by ghost** [comment] 2017-10-15 08:11
@hjr3
I just replace all version as "*" in `Cargo.toml`

**Comment by ghost** [comment] 2017-10-15 08:23
I can build php-rpm now, thanks.

**Closed as completed** 2017-10-15 08:23 UTC
